name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: log group test
      run: |
          echo "::group::test group"
          echo "testing"
          echo "::error:: test failed"
          exit 1
          echo "::endgroup::"
      shell: bash
    - name: Set Greeting
      if: always()
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}


